on:
  push:
    branches:
    - ACA
env:
  DOTNET_CORE_VERSION: 7.0.x
  CONTAINER_APP_NAME: librarymanagement.api-container-app
  CONTAINER_APP_ENVIRONMENT_NAME: cae-eastus
  RESOURCE_GROUP: LibraryACARG
  CONTAINER_REGISTRY_NAME: libraryacr
  CONTAINER_REGISTRY_LOGIN_SERVER: libraryacr.azurecr.io
jobs:
  BuildAndDeployContainerApp:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.cae_eastus_SPN }}
    - name: Container App deploy
      uses: azure/container-apps-deploy-action@v1
      with:
        appSourcePath: ${{ github.workspace }}
        acrName: ${{ env.CONTAINER_REGISTRY_NAME }}
        acrUsername: ${{ secrets.LibraryACR_USERNAME_26C0 }}
        acrPassword: ${{ secrets.LibraryACR_PASSWORD_26C0 }}
        imageToBuild: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.CONTAINER_APP_NAME }}:${{ github.sha }}
        containerAppName: ${{ env.CONTAINER_APP_NAME }}
        containerAppEnvironment: ${{ env.CONTAINER_APP_ENVIRONMENT_NAME }}
        resourceGroup: ${{ env.RESOURCE_GROUP }}
