name: Build and push image to registry and deploy to container app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/library-api-container-AutoDeployTrigger-536cd405-1a7b-432e-9a78-8639cf2434a4.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.LIBRARYAPICONTAINER_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.LIBRARYAPICONTAINER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.LIBRARYAPICONTAINER_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: libraryregistry.azurecr.io
          registryUsername: ${{ secrets.ACR_PASSWORD_LIBRARYREGISTRY }}
          registryPassword: ${{ secrets.ACR_USERNAME_LIBRARYREGISTRY }}
          containerAppName: library-api-container
          resourceGroup: Library
          imageToBuild: libraryregistry.azurecr.io/library-api-container:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


